// src/components/TabItem.vue
<template>
  <button
    class="tab"
    :class="{ active, current: tab.active }"
    @click="click"
    @mousedown="mouseDown"
    @focus="focus">
    <div class="favicon">
      <span v-if="!tab.favIconUrl"><TabbyIcon/></span>
      <img v-else :src="tab.favIconUrl">
    </div>
    <div class="text">
      <h1 v-if="tab.title_hl" :aria-label="tab.title" v-html="tab.title_hl"></h1>
      <h1 v-else>{{tab.title}}</h1>
      <p v-if="tab.url_hl" :aria-label="tab.url" v-html="tab.url_hl"></p>
      <p v-else>{{tab.url}}</p>
    </div>
    <div class="actions">
      <button @click="closeTab" :aria-label="$t('close-tab-button')" :tabindex="active ? 0 : -1"><CloseIcon /></button>
      <button
        v-if="tab.audible || tab.mutedInfo.muted"
        @click="muteTab"
        class="alwaysVisable"
        :class="{ enabled: tab.mutedInfo.muted }"
        :aria-label="tab.mutedInfo.muted ? $t('unmute-tab-button') : $t('mute-tab-button')"
        :tabindex="active ? 0 : -1"><AudioOffIcon v-if="tab.mutedInfo.muted" /><AudioOnIcon v-else /></button>
      <button
        @click="pinTab"
        :class="{ alwaysVisable: tab.pinned, enabled: tab.pinned }"
        :aria-label="tab.pinned ? $t('unpin-tab-button') : $t('pin-tab-button')"
        :tabindex="active ? 0 : -1"><PinIcon /></button>
    </div>
  </button>
</template>

<script>
import TabbyIcon from '@/assets/tabby_favicon.svg?inline'
import CloseIcon from '@/assets/close.svg?inline'
import PinIcon from '@/assets/push_pin.svg?inline'
import AudioOffIcon from '@/assets/volume_off.svg?inline'
import AudioOnIcon from '@/assets/volume_up.svg?inline'

export default {
  name: 'TabItem',
  props: {
    tab: Object,
    active: Boolean,
  },
  components: {
    TabbyIcon, CloseIcon, PinIcon, AudioOffIcon, AudioOnIcon,
  },
  methods: {
    click(e) {
      this.$emit('click', e)
    },
    mouseDown() {
      this.$emit('mouseDown', this.$el)
    },
    focus(e) {
      this.$emit('focus', e)
    },
    pinTab(e) {
      e.stopPropagation()
      this.$emit('pinTab', e)
    },
    closeTab(e) {
      e.stopPropagation()
      this.$emit('closeTab', e)
    },
    muteTab(e) {
      e.stopPropagation()
      this.$emit('muteTab', e)
    },
  },
}
</script>

<style lang="stylus">
@import "~@/assets/styles/palette"

.tab
  display flex
  border none
  background unset
  width 100%
  text-align left
  padding .9rem
  outline none
  .favicon, .actions
    display flex
    justify-content center
    align-items center
  .favicon
    margin-right 0.75rem
    width 2rem
    height 2rem
    border-radius 50%
    themed background background-odd
    span, img
      display block
      width 16px
      height 16px
      padding 2px
    span svg
      themed fill font-color
    img
      border-radius 4px
  .text
    flex 1
    min-width 0
    h1, p
      font-weight 400
      grid-column-start 2
      margin 0
      text-overflow ellipsis
      white-space nowrap
      overflow hidden
    h1
      font-size 15px
    p
      font-size 11px
      grid-row-start 2
  .actions
    margin-left 0.75rem
    button
      width 24px
      height 24px
      themed background background-odd
      border-radius 50%
      &:not(:last-child)
        margin-right .5rem
      svg
        themed fill font-color
        padding 3px
        width 18px
        height 18px
      &:focus
        outline none
        box-shadow 0 0 0 0.2rem rgba(255,255,255, .5)
      &:active
        box-shadow 0 0 0 0.4rem rgba(255,255,255, .75)
      &.enabled
        themed background-color accent-color
        svg
          themed fill background

  &:not(.active):not(:focus):not(:hover) .actions button:not(.alwaysVisable)
      display none

  .highlight
      padding 0
      padding-top .2em
      padding-bottom .2em
      margin 0
      background-color rgba(0, 0, 0, 0.03)
      border-radius 6px
      &::before, &::after
        letter-spacing -0.2em
        content "\00a0"
  &.current:not(.active)
    themed background-color background-odd
    .favicon, .actions button:not(.enabled)
      themed background-color background

  &.active, &:focus
    themed background-color accent-color
    themed color selected-color
    .actions button
      background rgba(0,0,0,0.1)
      svg
        fill white
      &.enabled
        background white
        svg
          themed fill accent-color
  .actions button:not(.enabled):focus
    outline none
    themed background-color background
    svg
      themed fill accent-color
</style>

// src/components/TabItem.svelte
<script lang="ts">
  import { _ } from 'svelte-i18n'
  import Button from 'tint/components/Button.svelte'
  import TabbyIcon from '@src/assets/icon.svg?raw'
  import iconAudio from 'tint/icons/20-volume-off.svg?raw'
  import iconAudioOff from 'tint/icons/20-volume-up.svg?raw'
  import iconPin from 'tint/icons/20-push-pin.svg?raw'
  import iconPinFill from 'tint/icons/20-push-pin-fill.svg?raw'
  import iconClose from 'tint/icons/20-close.svg?raw'
  import { onMount } from 'svelte'
  import type { HighlightResult } from '@src/utils/fuse-highlight'
  import * as extAPI from '@src/utils/extension-api'
  import { createEventDispatcher } from 'svelte'
  import tabGroups from '@src/utils/group-store'
  import containers from '@src/utils/container-store'
  import containerIcons from '@src/utils/container-icons'
  import state from '@src/utils/state-store'

  const dispatch = createEventDispatcher()

  export let tab: HighlightResult<extAPI.CombinedTab>
  export let nth: number
  export let focus: [number, number]
  export let claimFocus: boolean

  let buttons: (HTMLButtonElement | undefined)[] = [
    undefined,
    undefined,
    undefined,
    undefined,
  ]

  $: focusElement(focus)

  onMount(() => {
    focusElement(focus)
  })

  export const focusLeft = () => {
    if (!claimFocus) {
      return
    } else if (document.dir == 'rtl') moveFocusRight()
    else moveFocusLeft()
  }
  export const focusRight = () => {
    if (!claimFocus) {
      return
    } else if (document.dir == 'rtl') moveFocusLeft()
    else moveFocusRight()
  }

  function moveFocusLeft() {
    // find the next focusable element in buttons element.
    // if we reach the end of the list, do nothing
    let current = focus[1]
    while (current > 0) {
      current--
      if (buttons[current]) {
        focus = [focus[0], current]
        return
      }
    }
  }
  function moveFocusRight() {
    // find the next focusable element in buttons element.
    // if we reach the end of the list, do nothing
    let current = focus[1]
    while (current < buttons.length - 1) {
      current++
      if (buttons[current]) {
        focus = [focus[0], current]
        return
      }
    }
  }

  function focusElement(f: [number, number]) {
    // Skip if this tab is not focused or we don't want to claim focus
    if (f[0] !== nth) {
      return
    }
    buttons[0]?.scrollIntoView({
      behavior: claimFocus ? 'smooth' : 'instant',
      block: claimFocus ? 'nearest' : 'center',
    })
    if (!claimFocus) {
      return
    }
    // If the focus is 0, focus the first button
    if (f[1] === 0) {
      buttons[0]?.focus()
      return
    }
    // otherwise we try to select the button at the given index,
    // if it does not exist we go up until we find one that does
    for (let i = f[1]; i < buttons.length; i++) {
      if (buttons[i]) {
        buttons[i]?.focus()
        return
      }
    }
    // otherwise, focus the last button
    buttons[buttons.length - 1]?.focus()
  }

  function isFocused(f: [number, number], i: number) {
    return f[0] === nth && f[1] === i
  }

  function openTab() {
    tab?.id && extAPI.openTab(tab.id)
    dispatch('action-at', nth)
  }
  function togglePinTab() {
    tab?.id && extAPI.updateTabs(tab.id, { pinned: !tab.pinned })
    dispatch('action-at', nth)
  }
  function toggleMuteTab() {
    tab?.id &&
      extAPI.updateTabs(tab.id, {
        muted: !tab.mutedInfo?.muted ? true : false,
      })
    dispatch('action-at', nth)
  }
  function closeTab() {
    tab?.id && extAPI.closeTab(tab.id)
    dispatch('action-at', nth)
  }

  function runIfEnter<T extends (...args: any[]) => any>(
    e: KeyboardEvent,
    fn: T,
    ...args: Parameters<T>
  ) {
    if (e.key === 'Enter') {
      e.preventDefault()
      fn(...args)
    } else if (e.key === 'Home') {
      e.preventDefault()
      dispatch('focus-set', 0)
    } else if (e.key === 'End') {
      e.preventDefault()
      dispatch('focus-set', 1)
    }
  }
</script>

<li
  class:focus={isFocused(focus, 0)}
  class:current={tab.active}
  class={`chromeGroupColor ${$tabGroups[tab.groupId]?.color || ''}`}
>
  <button
    class="tab-button"
    bind:this={buttons[0]}
    tabindex={isFocused(focus, 0) ? 0 : -1}
    on:click={openTab}
    on:keydown={(e) => runIfEnter(e, openTab)}
  >
    <div
      class="favicon"
      class:grouped={$state.preferences?.showGroupTabs &&
        tab.groupId &&
        tab.groupId !== -1}
    >
      {#if tab.favIconUrl}
        <img src={tab.favIconUrl} alt="" />
      {:else}
        <span>{@html TabbyIcon}</span>
      {/if}
    </div>
    <div class="text">
      <h1 class="tint--type-ui">
        {#if tab.title_hl}
          {@html tab.title_hl}
        {:else}
          {tab.title}
        {/if}
      </h1>
      <div class="sub">
        {#if $state.preferences?.showContainerTabs && tab.cookieStoreId && tab.cookieStoreId !== 'firefox-default' && $containers[tab.cookieStoreId]}
          <p
            class={`tint--type-ui-small-bold container firefoxContainer ${
              $containers[tab.cookieStoreId].color
            }`}
          >
            <span aria-hidden="true"
              >{@html containerIcons[$containers[tab.cookieStoreId].icon]}</span
            >
            {$containers[tab.cookieStoreId].name}
          </p>
        {/if}
        <p class="tint--type-ui-small">
          {#if tab.url_hl}
            {@html tab.url_hl}
          {:else}
            {tab.url}
          {/if}
        </p>
      </div>
    </div>
  </button>
  <div class="actions">
    {#if tab.audible || tab.mutedInfo?.muted}
      <Button
        bind:element={buttons[1]}
        icon={true}
        on:click={toggleMuteTab}
        on:keydown={(e) => runIfEnter(e, toggleMuteTab)}
        small={true}
        tabindex={isFocused(focus, 1) ? 0 : -1}
        title="Mute tab"
        variant="ghost"
        >{@html tab.mutedInfo?.muted ? iconAudio : iconAudioOff}</Button
      >
    {/if}
    {#if tab.pinned || focus[0] === nth || true}
      <Button
        bind:element={buttons[2]}
        icon={true}
        on:click={togglePinTab}
        on:keydown={(e) => runIfEnter(e, togglePinTab)}
        small={true}
        tabindex={isFocused(focus, 2) ? 0 : -1}
        title="Pin tab"
        toggled={tab.pinned}
        variant="ghost">{@html tab.pinned ? iconPinFill : iconPin}</Button
      >
    {/if}
    <Button
      bind:element={buttons[3]}
      icon={true}
      on:click={closeTab}
      on:keydown={(e) => runIfEnter(e, closeTab)}
      small={true}
      tabindex={isFocused(focus, 3) ? 0 : -1}
      title="Close tab"
      variant="ghost"
      >{@html iconClose}
    </Button>
  </div>
</li>

<style lang="sass">
  li, .tab-button
    display: flex
    align-items: center

  .current
    background: var(--tint-input-bg)
    .favicon
      background: var(--tint-bg)

  .tab-button
    flex-grow: 1
    border: none
    border-radius: 0
    background: none
    padding: tint.$size-12
    text-transform: none
    text-align: start
    min-width: 0
    gap: tint.$size-16
    margin-inline-end: tint.$size-8
    border-top-right-radius: tint.$size-8
    border-bottom-right-radius: tint.$size-8
    position: relative
    .text
      flex-grow: 1
      min-width: 0
    &:focus
      outline: none
    &:active
      background: var(--tint-action-secondary-active)

  h1, p
    overflow: hidden
    text-overflow: ellipsis
    white-space: nowrap

  p
    color: var(--tint-text-secondary)
    margin-block-start: tint.$size-2

  .favicon.grouped
    outline: 2px solid var(--special-color-bg)
  .focus .favicon.grouped
    box-shadow: 0 0 0 4px #fff, inset 0 0 0 4px #fff
    @media (prefers-color-scheme: dark)
      box-shadow: 0 0 0 4px #00000066, inset 0 0 0 2px #00000066

  .favicon
    padding: tint.$size-12
    background: var(--tint-input-bg)
    line-height: 0
    border-radius: 50%
    > img, > span > :global(svg)
      width: tint.$size-16
      height: tint.$size-16
      fill: currentColor
    > span
      color: var(--tint-text-secondary)

  :global(.highlight)
    background: rgba(0,0,0, 0.05)
    box-shadow: inset 0 0 0 1px rgba(0,0,0, 0.1)

  .actions
    padding-inline-end: tint.$size-8
    flex-shrink: 0
    > :global(button:not(.primary))
      color: var(--tint-text)

  .focus
    background: var(--tint-action)
    color: var(--tint-action-text)
    .favicon
      background: #FFF
      @media (prefers-color-scheme: dark)
        background: #FFFFFF99
        span
          color: #FFF
    .tab-button, .tab-button p
      color: var(--tint-action-text)
    .actions > :global(button)
      color: var(--tint-action-text)


  .sub
    display: flex
    flex-direction: row
    // every item after the last one gets a utf-8 dot after it
    > :global(p:not(:first-child))::before
      content: '—'
      margin-inline: tint.$size-4

  .container
    display: flex
    align-items: center
    gap: tint.$size-4
    flex-shrink: 0
    color: var(--special-color)
    span
      line-height: 0
    :global(> span > svg)
      height: tint.$size-12
      width: tint.$size-12
</style>
