// src/App.vue
<template>
  <div id="app">
    <Preferences v-if="showPreferences" @close="setPreferences(false)" />
    <Search v-else @showSettings="setPreferences(true)" />
  </div>
</template>

<script>
import Search from '@/components/Search.vue'
import Preferences from '@/components/Preferences.vue'

export default {
  name: 'App',
  components: {
    Search, Preferences,
  },
  data () {
    return {
      showPreferences: false,
    }
  },
  methods: {
    setPreferences(value) {
      this.showPreferences = value
    },
  },
}
</script>

<style lang="stylus">
@import "~@/assets/styles/palette"
@import "~@/assets/styles/mixins"

  input, button
    padding 0
    border none
    color inherit
    background unset
  html
    themed color font-color
    themed background background
    remove-native()
  html, body
    margin 0
    width 600px
    height 100%
    font-family -apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif
  #app > *
    max-height 500px
    display flex
    flex-direction column
    .top-bar, .bottom-bar
      flex-shrink 0
    .content
      flex 1
      overflow-y auto
  hr
    margin 0
    border 0
    height 0
    themed border-bottom seperator-color 1px solid
</style>

// src/App.svelte
<script lang="ts">
  import Preferences from '@src/Preferences.svelte'
  import Search from '@src/Search.svelte'

  let showPreferences = false
</script>

<div id="app" class="tint--type-ui tint--plain">
  {#if showPreferences}
    <Preferences on:toggle-preferences={() => (showPreferences = false)} />
  {:else}
    <Search on:toggle-preferences={() => (showPreferences = true)} />
  {/if}
</div>

<style lang="sass">
  #app
    max-height: 500px
    display: flex
    flex-direction: column
    background: var(--tint-bg)
    color: var(--tint-text)
    flex-grow: 1
    > :global(header)
      padding: tint.$size-4 tint.$size-8
      gap: tint.$size-12
      align-items: center
      display: flex
      background: var(--tint-bg)
      border-bottom: 1px solid var(--tint-input-bg)
      flex-shrink: 0
    > :global(.main-area)
      flex-grow: 1
      overflow-x: auto
      background: var(--tint-bg)
    > :global(.infobar)
      padding: tint.$size-4 tint.$size-8
      gap: tint.$size-12
      align-items: center
      display: flex
      background: var(--tint-input-bg)
      flex-shrink: 0
    > :global(.infobar > *)
      flex-grow: 1
</style>
